version: '3.9'

services:
  heyerapp_django:
    volumes:
      - static:/app/staticfiles
    build:
      context: .
    ports:
      - "8000:8000"
    image: nickheyer/heyerapp-django:latest
    env_file:
      - /etc/django.env

volumes:
  static:
