version: '3.9'

services:
  
  heyer_app_django:
    volumes:
      - static:/static
    build:
      context: .
    expose:
      - "8000"
  
  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - heyer_app_django

volumes:
  static: 
