version: '3.9'

services:
  
  heyerapp-django:
    volumes:
      - static:/static
    build:
      context: .
    expose:
      - "8000"
    image: nickheyer/heyerapp-django:latest
  
  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - heyerapp-django
    image: nickheyer/heyerapp-nginx:latest

volumes:
  static:
