version: '3.9'

services:
  
  heyerapp_django:
    volumes:
      - static:/static
    build:
      context: .
    expose:
      - "8000"
    image: nickheyer/heyerapp-django:latest
    env_file:
      - ~/environment/django.env

  nginx:
    build: ./nginx
    env_file:
      - ./nginx/nginx-certbot.env
    volumes:
      - static:/static
      - nginx_secrets:/etc/letsencrypt
      - ./user_conf.d:/etc/nginx/user_conf.d
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - heyerapp_django
    image: nickheyer/heyerapp-nginx:latest
    

volumes:
  nginx_secrets:
  static:
