# Generated by Django 4.1 on 2022-09-09 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='description',
            field=models.CharField(default=None, max_length=2048, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='experience',
            name='position',
            field=models.CharField(default=None, max_length=128, verbose_name='Position'),
        ),
    ]
