# Generated by Django 4.1 on 2022-09-25 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0005_alter_certification_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='image',
            field=models.URLField(default='https://via.placeholder.com/60C/O', max_length=128, verbose_name='Image'),
        ),
    ]
