# Generated by Django 4.1 on 2022-09-25 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0006_education_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='link',
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(default=None, max_length=2048, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='project',
            name='live_demo',
            field=models.URLField(default=None, max_length=256, verbose_name='Live Demo'),
        ),
        migrations.AddField(
            model_name='project',
            name='repository',
            field=models.URLField(default=None, max_length=256, verbose_name='Repository'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='link',
            field=models.URLField(default='https://heyer.app', max_length=256, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Name'),
        ),
    ]
