# Generated by Django 4.1 on 2022-09-25 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0007_remove_project_link_project_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='languages',
            field=models.CharField(default=None, max_length=256, verbose_name='Languages'),
        ),
    ]
