# Generated by Django 4.1 on 2022-09-25 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0009_alter_project_live_demo_alter_project_repository'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='live_demo',
            field=models.URLField(blank=True, default=None, max_length=256, verbose_name='Live Demo'),
        ),
        migrations.AlterField(
            model_name='project',
            name='repository',
            field=models.URLField(blank=True, default=None, max_length=256, verbose_name='Repository'),
        ),
    ]
