# Generated by Django 4.1 on 2022-09-25 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0010_alter_project_live_demo_alter_project_repository'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='skill_used',
            field=models.ManyToManyField(blank=True, default=None, to='Portfolio.skill', verbose_name='Skills Used'),
        ),
    ]
