# Generated by Django 4.1 on 2022-09-25 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0011_project_skill_used'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['name', 'years'], 'verbose_name': 'Skill', 'verbose_name_plural': 'Skills'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='languages',
        ),
        migrations.AlterField(
            model_name='certification',
            name='cert_name',
            field=models.CharField(default='Proficiency Certificate', max_length=256, verbose_name='Certificate Name'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='certifier',
            field=models.CharField(max_length=256, verbose_name='Certifier'),
        ),
        migrations.AlterField(
            model_name='education',
            name='image',
            field=models.URLField(default='https://via.placeholder.com/60C/O', max_length=256, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='education',
            name='institute',
            field=models.CharField(max_length=256, verbose_name='Institute'),
        ),
        migrations.AlterField(
            model_name='education',
            name='link',
            field=models.URLField(default='https://heyer.app', max_length=256, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='company',
            field=models.CharField(max_length=256, verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='link',
            field=models.URLField(default='https://heyer.app', max_length=256, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='position',
            field=models.CharField(default=None, max_length=256, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='project',
            name='skill_used',
            field=models.ManyToManyField(blank=True, default=None, related_name='skills', to='Portfolio.skill', verbose_name='Skills Used'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='image',
            field=models.URLField(default='https://via.placeholder.com/60C/O', max_length=256, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='link',
            field=models.URLField(default='https://heyer.app', max_length=256, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Name'),
        ),
    ]
