# Generated by Django 4.1 on 2022-09-29 23:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0013_alter_certification_options_alter_experience_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=256, verbose_name='Source')),
                ('description', models.CharField(default=None, max_length=2048, verbose_name='Description')),
                ('datetime_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date and Time Created')),
            ],
            options={
                'verbose_name': 'Feed Event',
                'verbose_name_plural': 'Feed Events',
                'ordering': ['datetime_created'],
            },
        ),
    ]
