# Generated by Django 4.1 on 2022-09-29 23:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0014_feedevent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedevent',
            options={'ordering': ['eventdate'], 'verbose_name': 'Feed Event', 'verbose_name_plural': 'Feed Events'},
        ),
        migrations.RemoveField(
            model_name='feedevent',
            name='datetime_created',
        ),
        migrations.AddField(
            model_name='feedevent',
            name='eventdate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date and Time of Event'),
        ),
    ]
