# Generated by Django 4.1 on 2022-09-30 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0015_alter_feedevent_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedevent',
            options={'ordering': ['-eventdate'], 'verbose_name': 'Feed Event', 'verbose_name_plural': 'Feed Events'},
        ),
    ]
