# Generated by Django 4.1 on 2022-09-30 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0016_alter_feedevent_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedevent',
            name='link',
            field=models.URLField(default='https://heyer.app', max_length=256, verbose_name='Link'),
        ),
    ]
