# Generated by Django 4.1 on 2022-09-30 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0017_feedevent_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedevent',
            name='link',
            field=models.URLField(default=None, max_length=256, verbose_name='Link'),
        ),
    ]
