# Generated by Django 4.1 on 2022-09-30 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0019_alter_feedevent_eventdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedevent',
            name='eventdate',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date and Time of Event'),
        ),
    ]
