# Generated by Django 4.1 on 2022-09-30 05:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0020_alter_feedevent_eventdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedevent',
            name='eventdate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date and Time of Event'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedevent',
            name='link',
            field=models.URLField(default=None, max_length=256, null=True, verbose_name='Link'),
        ),
    ]
