# Generated by Django 4.1 on 2022-10-03 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0021_alter_feedevent_eventdate_alter_feedevent_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentStatus', models.JSONField(verbose_name='Current Status')),
                ('eventdate', models.DateTimeField(auto_now_add=True, verbose_name='Date and Time of Event')),
            ],
        ),
    ]
