name: Build and Deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      onlyDeploy:
        description: 'Run only deploy?'
        required: true
        default: 'no'

jobs:
  build:
    runs-on: [self-hosted, dev]
    if: github.event.inputs.onlyDeploy != 'yes'  # This conditional skips the build job if 'onlyDeploy' is 'yes'
    steps:
      - name: Build docker containers      
        run: |
          echo "Changing Dir"
          cd ~/code/HeyerApp
          docker-compose build
          docker-compose push
          
  deploy:
    needs: build
    runs-on: [self-hosted, prod]
    if: always()
    steps:
      - uses: actions/checkout@v3
      - name: Updating container
        run: |
          echo "Pulling images"
          cd /opt/compose
          docker-compose down
          docker-compose pull
          docker-compose up -d

  
  send-request:
    # The type of runner that the job will run on
    needs: deploy
    runs-on: [self-hosted, dev]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: Send
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://heyer.app/miscapi/feedevent/'
          method: 'POST'
          customHeaders: '{"Content-Type": "application/json", "Authorization":"${{ secrets.FEED_TOKEN }}"}'
          data: '{"source": "Github", "description": "Pushed commit to ${{github.event.repository.full_name}}: ${{ github.event.head_commit.message }}", "link":"${{github.event.repository.url}}"}'
