# This is a basic workflow to help you get started with Actions

name: Build and Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [self-hosted, dev]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: Update requirements
        run: |
          
          echo Changing Dir
          cd ~/code/HeyerApp
          echo Activating venv
          source venv/bin/activate
          echo Updating requirements file
          pip freeze > requirements.txt
          echo Deactivating
          deactivate
  
      - name: Build docker containers      
        run: |
          echo Changing Dir
          cd ~/code/HeyerApp
          echo Building containers
          $echo 1browser | sudo -S <command>
          chown -R $USER '/home/nickheyer/code/HeyerApp/data/certbot/conf/accounts'
          docker-compose build
          docker-compose push
          
  # This workflow contains a single job called "deploy"
  deploy:
    needs: build
    # The type of runner that the job will run on
    runs-on: [self-hosted, prod]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      - name: Update requirements
        run: |
          echo Pulling images
          cd $GITHUB_WORKSPACE
          sudo docker-compose down
          sudo docker-compose pull
          sudo docker-compose up -d --build
          sudo docker image prune -f

  

